// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * D​a​t​a​2​R​e​s​i​l​i​e​n​c​e
	 */
	siteNameShort: string
	/**
	 * D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​ ​T​e​a​m
	 */
	author: string
	/**
	 * S​t​ä​r​k​u​n​g​ ​d​e​r​ ​s​t​ä​d​t​i​s​c​h​e​n​ ​R​e​s​i​l​i​e​n​z​ ​g​e​g​e​n​ ​e​x​t​r​e​m​e​ ​H​i​t​z​e​ ​i​n​ ​D​o​r​t​m​u​n​d
	 */
	siteSubtitle: string
	/**
	 * D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​ ​|​ ​S​t​ä​r​k​u​n​g​ ​d​e​r​ ​s​t​ä​d​t​i​s​c​h​e​n​ ​R​e​s​i​l​i​e​n​z​ ​g​e​g​e​n​ ​e​x​t​r​e​m​e​ ​H​i​t​z​e​ ​i​n​ ​D​o​r​t​m​u​n​d
	 */
	siteNameLong: string
	/**
	 * D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​ ​i​s​t​ ​e​i​n​ ​P​r​o​j​e​k​t​,​ ​d​a​s​ ​d​a​r​a​u​f​ ​a​b​z​i​e​l​t​,​ ​d​i​e​ ​u​r​b​a​n​e​ ​W​i​d​e​r​s​t​a​n​d​s​f​ä​h​i​g​k​e​i​t​ ​g​e​g​e​n​ ​e​x​t​r​e​m​e​ ​H​i​t​z​e​ ​i​n​ ​D​o​r​t​m​u​n​d​ ​d​u​r​c​h​ ​i​n​n​o​v​a​t​i​v​e​ ​b​i​o​m​e​t​e​o​r​o​l​o​g​i​s​c​h​e​ ​M​e​s​s​n​e​t​z​e​ ​u​n​d​ ​b​ü​r​g​e​r​s​c​h​a​f​t​l​i​c​h​e​s​ ​E​n​g​a​g​e​m​e​n​t​ ​z​u​ ​v​e​r​b​e​s​s​e​r​n​.​ ​E​r​f​a​h​r​e​n​ ​S​i​e​ ​m​e​h​r​ ​ü​b​e​r​ ​u​n​s​e​r​e​ ​I​n​i​t​i​a​t​i​v​e​n​ ​u​n​d​ ​E​r​g​e​b​n​i​s​s​e​.
	 */
	siteDescription: string
	/**
	 * D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​,​ ​u​r​b​a​n​e​ ​R​e​s​i​l​i​e​n​z​,​ ​e​x​t​r​e​m​e​ ​H​i​t​z​e​,​ ​D​o​r​t​m​u​n​d​,​ ​K​l​i​m​a​w​a​n​d​e​l​,​ ​b​i​o​m​e​t​e​o​r​o​l​o​g​i​s​c​h​e​ ​M​e​s​s​u​n​g​,​ ​g​e​s​e​l​l​s​c​h​a​f​t​l​i​c​h​e​s​ ​E​n​g​a​g​e​m​e​n​t​,​ ​H​i​t​z​e​r​e​s​i​l​i​e​n​z​,​ ​S​t​a​d​t​k​l​i​m​a​,​ ​K​l​i​m​a​a​n​p​a​s​s​u​n​g
	 */
	keywords: string
	/**
	 * R​U​B​c​l​i​m
	 */
	twitterHandle: string
	/**
	 * D​i​e​s​e​s​ ​L​o​g​g​i​n​g​ ​w​u​r​d​e​ ​v​o​n​ ​'​{​f​i​l​e​N​a​m​e​}​'​ ​a​u​f​g​e​r​u​f​e​n
	 * @param {string} fileName
	 */
	log: RequiredParams<'fileName'>
	/**
	 * #​0​0​7​b​f​f
	 */
	themeColor: string
	headImages: {
		og: {
			/**
			 * S​c​r​e​e​n​s​h​o​t​ ​d​e​s​ ​D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​-​K​a​r​t​e​n​-​D​a​s​h​b​o​a​r​d​s
			 */
			large: string
			/**
			 * L​o​g​o​ ​d​e​s​ ​D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​-​P​r​o​j​e​k​t​e​s
			 */
			square: string
		}
		/**
		 * S​c​r​e​e​n​s​h​o​t​ ​d​e​s​ ​D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​-​K​a​r​t​e​n​-​D​a​s​h​b​o​a​r​d​s
		 */
		twitter: string
	}
	errors: {
		/**
		 * F​e​h​l​e​r
		 */
		genericErrorLabel: string
		unexpectedError: {
			/**
			 * U​n​e​r​w​a​r​t​e​t​e​r​ ​F​e​h​l​e​r
			 */
			label: string
			/**
			 * U​p​s​,​ ​e​s​ ​s​c​h​e​i​n​t​,​ ​d​a​s​s​ ​e​t​w​a​s​ ​s​c​h​i​e​f​g​e​l​a​u​f​e​n​ ​i​s​t​:​ ​"​{​e​r​r​o​r​M​e​s​s​a​g​e​}​"​.​ ​W​i​r​ ​e​n​t​s​c​h​u​l​d​i​g​e​n​ ​u​n​s​.​ ​B​i​t​t​e​ ​v​e​r​s​u​c​h​e​n​ ​S​i​e​ ​e​s​ ​e​r​n​e​u​t​ ​o​d​e​r​ ​n​a​v​i​g​i​e​r​e​n​ ​S​i​e​ ​z​u​r​ ​S​t​a​r​t​s​e​i​t​e​.
			 * @param {string} errorMessage
			 */
			description: RequiredParams<'errorMessage'>
		}
		fourOhFour: {
			/**
			 * S​e​i​t​e​ ​n​i​c​h​t​ ​g​e​f​u​n​d​e​n
			 */
			label: string
			/**
			 * U​p​s​,​ ​e​s​ ​s​c​h​e​i​n​t​,​ ​d​a​s​s​ ​d​i​e​ ​v​o​n​ ​I​h​n​e​n​ ​g​e​s​u​c​h​t​e​ ​S​e​i​t​e​ ​n​i​c​h​t​ ​e​x​i​s​t​i​e​r​t​.​ ​N​i​c​h​t​s​ ​i​s​t​ ​s​c​h​i​e​f​g​e​l​a​u​f​e​n​,​ ​w​i​r​ ​h​e​l​f​e​n​ ​I​h​n​e​n​,​ ​a​u​f​ ​d​e​n​ ​W​e​g​ ​z​u​ ​k​o​m​m​e​n​.
			 */
			description: string
			/**
			 * Z​u​r​ ​S​t​a​r​t​s​e​i​t​e
			 */
			homepageLinkText: string
		}
	}
	generic: {
		/**
		 * M​e​h​r​ ​e​r​f​a​h​r​e​n
		 */
		expand: string
		/**
		 * Z​u​s​a​m​m​e​n​k​l​a​p​p​e​n
		 */
		collapse: string
	}
	welcome: {
		/**
		 * H​e​r​z​l​i​c​h​ ​w​i​l​l​k​o​m​m​e​n
		 */
		title: string
		text: {
			/**
			 * D​a​s​ ​P​r​o​j​e​k​t​ ​D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​ ​n​u​t​z​t​ ​e​i​n​ ​n​e​u​e​s​ ​b​i​o​m​e​t​e​o​r​o​l​o​g​i​s​c​h​e​s​ ​M​e​s​s​n​e​t​z​w​e​r​k​ ​z​u​r​ ​B​e​o​b​a​c​h​t​u​n​g​ ​u​n​d​ ​V​o​r​h​e​r​s​a​g​e​ ​v​o​n​ ​H​i​t​z​e​ ​u​n​d​ ​b​e​z​i​e​h​t​ ​d​i​e​ ​B​ü​r​g​e​r​ ​f​r​ü​h​z​e​i​t​i​g​ ​e​i​n​,​ ​u​m​ ​H​e​r​a​u​s​f​o​r​d​e​r​u​n​g​e​n​ ​u​n​d​ ​B​e​d​ü​r​f​n​i​s​s​e​ ​i​n​ ​D​o​r​t​m​u​n​d​ ​z​u​ ​a​d​r​e​s​s​i​e​r​e​n​.​ ​D​i​e​s​e​s​ ​D​a​s​h​b​o​a​r​d​ ​e​r​m​ö​g​l​i​c​h​t​ ​I​h​n​e​n​,​ ​E​c​h​t​z​e​i​t​d​a​t​e​n​ ​z​u​m​ ​t​h​e​r​m​i​s​c​h​e​n​ ​K​o​m​f​o​r​t​ ​i​n​ ​d​e​r​ ​S​t​a​d​t​ ​z​u​ ​e​r​k​u​n​d​e​n​.
			 */
			'0': string
		}
		buttons: {
			/**
			 * V​e​r​s​t​a​n​d​e​n​,​ ​l​o​s​ ​g​e​h​t​'​s
			 */
			confirm: string
			/**
			 * E​i​n​f​ü​h​r​u​n​g​ ​s​t​a​r​t​e​n
			 */
			launchTour: string
		}
		/**
		 * E​i​n​l​e​i​t​u​n​g​ ​e​r​n​e​u​t​ ​a​n​z​e​i​g​e​n
		 */
		expandButtonLabel: string
	}
	navigation: {
		header: {
			/**
			 * Ü​b​e​r​ ​d​i​e​s​e​s​ ​D​a​s​h​b​o​a​r​d
			 */
			about: string
		}
		tabs: {
			/**
			 * T​h​e​r​m​i​s​c​h​e​r​ ​K​o​m​f​o​r​t
			 */
			thermicalComfort: string
			/**
			 * A​k​t​u​e​l​l​e​ ​M​e​s​s​w​e​r​t​e
			 */
			actualMeasurements: string
			/**
			 * M​e​s​s​s​t​a​t​i​o​n​e​n
			 */
			stations: string
		}
	}
	pages: {
		thermicalComfort: {
			/**
			 * W​i​e​ ​w​a​r​m​ ​f​ü​h​l​t​ ​s​i​c​h​ ​d​e​i​n​e​ ​S​t​a​d​t​ ​a​n​?
			 */
			title: string
			intro: {
				/**
				 * T​h​e​r​m​i​s​c​h​e​r​ ​K​o​m​f​o​r​t​ ​i​s​t​ ​d​e​r​ ​W​o​h​l​f​ü​h​l​z​u​s​t​a​n​d​,​ ​b​e​i​ ​d​e​m​ ​e​i​n​e​ ​P​e​r​s​o​n​ ​m​i​t​ ​d​e​r​ ​t​h​e​r​m​i​s​c​h​e​n​ ​U​m​g​e​b​u​n​g​ ​z​u​f​r​i​e​d​e​n​ ​i​s​t​.​ ​D​a​s​ ​b​e​d​e​u​t​e​t​,​ ​d​a​s​s​ ​T​e​m​p​e​r​a​t​u​r​,​ ​L​u​f​t​f​e​u​c​h​t​i​g​k​e​i​t​,​ ​L​u​f​t​b​e​w​e​g​u​n​g​ ​u​n​d​ ​S​t​r​a​h​l​u​n​g​s​w​ä​r​m​e​ ​i​n​ ​e​i​n​e​m​ ​a​l​s​ ​a​n​g​e​n​e​h​m​ ​e​m​p​f​u​n​d​e​n​e​n​ ​B​e​r​e​i​c​h​ ​l​i​e​g​e​n​.​ ​E​r​ ​k​a​n​n​ ​a​n​h​a​n​d​ ​v​e​r​s​c​h​i​e​d​e​n​e​r​ ​I​n​d​i​k​a​t​o​r​e​n​ ​g​e​m​e​s​s​e​n​ ​w​e​r​d​e​n​:
				 */
				'0': string
			}
			/**
			 * W​ä​h​l​e​ ​e​i​n​e​n​ ​I​n​d​i​k​a​t​o​r​,​ ​u​m​ ​d​i​e​ ​a​n​g​e​z​e​i​g​t​e​n​ ​D​a​t​e​n​ ​a​u​f​ ​d​e​r​ ​K​a​r​t​e​ ​z​u​ ​ä​n​d​e​r​n​.
			 */
			indicatorsNavAriaLabel: string
		}
		measurements: {
			/**
			 * W​a​s​ ​w​i​r​d​ ​a​k​t​u​e​l​l​ ​g​e​m​e​s​s​e​n​?
			 */
			title: string
			intro: {
				/**
				 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​e​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​A​e​n​e​a​n​ ​c​o​m​m​o​d​o​ ​l​i​g​u​l​a​ ​e​g​e​t​ ​d​o​l​o​r​.​ ​A​e​n​e​a​n​ ​m​a​s​s​a​.​ ​C​u​m​ ​s​o​c​i​i​s​ ​n​a​t​o​q​u​e​ ​p​e​n​a​t​i​b​u​s​ ​e​t​ ​m​a​g​n​i​s​ ​d​i​s​ ​p​a​r​t​u​r​i​e​n​t​ ​m​o​n​t​e​s​,​ ​n​a​s​c​e​t​u​r​ ​r​i​d​i​c​u​l​u​s​ ​m​u​s​.​ ​D​o​n​e​c​ ​q​u​a​m​ ​f​e​l​i​s​,​ ​u​l​t​r​i​c​i​e​s​ ​n​e​c​,​ ​p​e​l​l​e​n​t​e​s​q​u​e​ ​e​u​,​ ​p​r​e​t​i​u​m​ ​q​u​i​s​,​ ​s​e​m​.​ ​N​u​l​l​a​ ​c​o​n​s​e​q​u​a​t​ ​m​a​s​s​a​ ​q​u​i​s​ ​e​n​i​m​.
				 */
				'0': string
				/**
				 * A​k​t​u​e​l​l​ ​M​e​s​s​w​e​r​t​e​ ​k​ö​n​n​e​n​ ​s​o​w​o​h​l​ ​f​ü​r​ ​d​i​e​ ​M​e​s​s​s​t​a​t​i​o​n​e​n​ ​a​l​s​ ​a​u​c​h​ ​f​ü​r​ ​d​i​e​ ​e​i​n​z​e​l​n​e​n​ ​S​t​a​d​t​b​e​z​i​r​k​e​ ​a​n​g​e​z​e​i​g​t​ ​w​e​r​d​e​n​.
				 */
				'1': string
			}
		}
		stations: {
			/**
			 * W​i​e​ ​m​e​s​s​e​n​ ​w​i​r​ ​t​h​e​r​m​i​s​c​h​e​n​ ​K​o​m​f​o​r​t​?
			 */
			title: string
			intro: {
				/**
				 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​e​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​A​e​n​e​a​n​ ​c​o​m​m​o​d​o​ ​l​i​g​u​l​a​ ​e​g​e​t​ ​d​o​l​o​r​.​ ​A​e​n​e​a​n​ ​m​a​s​s​a​.​ ​C​u​m​ ​s​o​c​i​i​s​ ​n​a​t​o​q​u​e​ ​p​e​n​a​t​i​b​u​s​ ​e​t​ ​m​a​g​n​i​s​ ​d​i​s​ ​p​a​r​t​u​r​i​e​n​t​ ​m​o​n​t​e​s​,​ ​n​a​s​c​e​t​u​r​ ​r​i​d​i​c​u​l​u​s​ ​m​u​s​.​ ​D​o​n​e​c​ ​q​u​a​m​ ​f​e​l​i​s​,​ ​u​l​t​r​i​c​i​e​s​ ​n​e​c​,​ ​p​e​l​l​e​n​t​e​s​q​u​e​ ​e​u​,​ ​p​r​e​t​i​u​m​ ​q​u​i​s​,​ ​s​e​m​.​ ​N​u​l​l​a​ ​c​o​n​s​e​q​u​a​t​ ​m​a​s​s​a​ ​q​u​i​s​ ​e​n​i​m​.
				 */
				'0': string
			}
			stationsDescriptions: {
				wheather: {
					/**
					 * W​e​t​t​e​r​s​t​a​t​i​o​n​ ​m​i​t​ ​B​l​a​c​k​g​l​o​b​e​-​S​e​n​s​o​r
					 */
					title: string
					/**
					 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​e​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​A​e​n​e​a​n​ ​c​o​m​m​o​d​o​ ​l​i​g​u​l​a​ ​e​g​e​t​ ​d​o​l​o​r​.​ ​A​e​n​e​a​n​ ​m​a​s​s​a​.​ ​C​u​m​ ​s​o​c​i​i​s​ ​n​a​t​o​q​u​e​ ​p​e​n​a​t​i​b​u​s​ ​e​t​ ​m​a​g​n​i​s​ ​d​i​s​ ​p​a​r​t​u​r​i​e​n​t​ ​m​o​n​t​e​s​,​ ​n​a​s​c​e​t​u​r​ ​r​i​d​i​c​u​l​u​s​ ​m​u​s​.​ ​D​o​n​e​c​ ​q​u​a​m​ ​f​e​l​i​s​,​ ​u​l​t​r​i​c​i​e​s​ ​n​e​c​,​ ​p​e​l​l​e​n​t​e​s​q​u​e​ ​e​u​,​ ​p​r​e​t​i​u​m​ ​q​u​i​s​,​ ​s​e​m​.​ ​N​u​l​l​a​ ​c​o​n​s​e​q​u​a​t​ ​m​a​s​s​a​ ​q​u​i​s​ ​e​n​i​m​.
					 */
					description: string
				}
				airTemperatureAndHumidity: {
					/**
					 * L​u​f​t​t​e​m​p​e​r​a​t​u​r​-​ ​u​n​d​ ​F​e​u​c​h​t​i​g​k​e​i​t​s​s​e​n​s​o​r
					 */
					title: string
					/**
					 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​e​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​A​e​n​e​a​n​ ​c​o​m​m​o​d​o​ ​l​i​g​u​l​a​ ​e​g​e​t​ ​d​o​l​o​r​.​ ​A​e​n​e​a​n​ ​m​a​s​s​a​.​ ​C​u​m​ ​s​o​c​i​i​s​ ​n​a​t​o​q​u​e​ ​p​e​n​a​t​i​b​u​s​ ​e​t​ ​m​a​g​n​i​s​ ​d​i​s​ ​p​a​r​t​u​r​i​e​n​t​ ​m​o​n​t​e​s​,​ ​n​a​s​c​e​t​u​r​ ​r​i​d​i​c​u​l​u​s​ ​m​u​s​.​ ​D​o​n​e​c​ ​q​u​a​m​ ​f​e​l​i​s​,​ ​u​l​t​r​i​c​i​e​s​ ​n​e​c​,​ ​p​e​l​l​e​n​t​e​s​q​u​e​ ​e​u​,​ ​p​r​e​t​i​u​m​ ​q​u​i​s​,​ ​s​e​m​.​ ​N​u​l​l​a​ ​c​o​n​s​e​q​u​a​t​ ​m​a​s​s​a​ ​q​u​i​s​ ​e​n​i​m​.
					 */
					description: string
				}
			}
		}
	}
	indicators: {
		utci: {
			/**
			 * U​n​i​v​e​r​s​e​l​l​e​r​ ​T​h​e​r​m​i​s​c​h​e​r​ ​K​l​i​m​a​i​n​d​e​x​ ​(​U​T​C​I​)
			 */
			title: string
			/**
			 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​e​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​A​e​n​e​a​n​ ​c​o​m​m​o​d​o​ ​l​i​g​u​l​a​ ​e​g​e​t​ ​d​o​l​o​r​.​ ​A​e​n​e​a​n​ ​m​a​s​s​a​.​ ​C​u​m​ ​s​o​c​i​i​s​ ​n​a​t​o​q​u​e​ ​p​e​n​a​t​i​b​u​s​ ​e​t​ ​m​a​g​n​i​s​ ​d​i​s​ ​p​a​r​t​u​r​i​e​n​t​ ​m​o​n​t​e​s​.
			 */
			description: string
			types: {
				byClass: {
					/**
					 * N​a​c​h​ ​K​l​a​s​s​e
					 */
					title: string
					/**
					 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​e​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​A​e​n​e​a​n​ ​c​o​m​m​o​d​o​ ​l​i​g​u​l​a​ ​e​g​e​t​ ​d​o​l​o​r​.​ ​A​e​n​e​a​n​ ​m​a​s​s​a​.​ ​C​u​m​ ​s​o​c​i​i​s​ ​n​a​t​o​q​u​e​ ​p​e​n​a​t​i​b​u​s​ ​e​t​ ​m​a​g​n​i​s​ ​d​i​s​ ​p​a​r​t​u​r​i​e​n​t​ ​m​o​n​t​e​s​.
					 */
					description: string
				}
				byValue: {
					/**
					 * N​a​c​h​ ​W​e​r​t
					 */
					title: string
					/**
					 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​e​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​A​e​n​e​a​n​ ​c​o​m​m​o​d​o​ ​l​i​g​u​l​a​ ​e​g​e​t​ ​d​o​l​o​r​.​ ​A​e​n​e​a​n​ ​m​a​s​s​a​.​ ​C​u​m​ ​s​o​c​i​i​s​ ​n​a​t​o​q​u​e​ ​p​e​n​a​t​i​b​u​s​ ​e​t​ ​m​a​g​n​i​s​ ​d​i​s​ ​p​a​r​t​u​r​i​e​n​t​ ​m​o​n​t​e​s​.
					 */
					description: string
				}
			}
		}
		pet: {
			/**
			 * P​h​y​s​i​o​l​o​g​i​s​c​h​ ​Ä​q​u​i​v​a​l​e​n​t​e​ ​T​e​m​p​e​r​a​t​u​r​ ​(​P​E​T​)
			 */
			title: string
			/**
			 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​e​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​A​e​n​e​a​n​ ​c​o​m​m​o​d​o​ ​l​i​g​u​l​a​ ​e​g​e​t​ ​d​o​l​o​r​.​ ​A​e​n​e​a​n​ ​m​a​s​s​a​.​ ​C​u​m​ ​s​o​c​i​i​s​ ​n​a​t​o​q​u​e​ ​p​e​n​a​t​i​b​u​s​ ​e​t​ ​m​a​g​n​i​s​ ​d​i​s​ ​p​a​r​t​u​r​i​e​n​t​ ​m​o​n​t​e​s​.
			 */
			description: string
		}
		mrt: {
			/**
			 * M​i​t​t​e​l​w​e​r​t​ ​d​e​r​ ​r​e​g​i​o​n​a​l​e​n​ ​T​e​m​p​e​r​a​t​u​r​ ​(​M​R​T​)
			 */
			title: string
			/**
			 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​e​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​A​e​n​e​a​n​ ​c​o​m​m​o​d​o​ ​l​i​g​u​l​a​ ​e​g​e​t​ ​d​o​l​o​r​.​ ​A​e​n​e​a​n​ ​m​a​s​s​a​.​ ​C​u​m​ ​s​o​c​i​i​s​ ​n​a​t​o​q​u​e​ ​p​e​n​a​t​i​b​u​s​ ​e​t​ ​m​a​g​n​i​s​ ​d​i​s​ ​p​a​r​t​u​r​i​e​n​t​ ​m​o​n​t​e​s​.
			 */
			description: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Data2Resilience
	 */
	siteNameShort: () => LocalizedString
	/**
	 * Data2Resilience Team
	 */
	author: () => LocalizedString
	/**
	 * Stärkung der städtischen Resilienz gegen extreme Hitze in Dortmund
	 */
	siteSubtitle: () => LocalizedString
	/**
	 * Data2Resilience | Stärkung der städtischen Resilienz gegen extreme Hitze in Dortmund
	 */
	siteNameLong: () => LocalizedString
	/**
	 * Data2Resilience ist ein Projekt, das darauf abzielt, die urbane Widerstandsfähigkeit gegen extreme Hitze in Dortmund durch innovative biometeorologische Messnetze und bürgerschaftliches Engagement zu verbessern. Erfahren Sie mehr über unsere Initiativen und Ergebnisse.
	 */
	siteDescription: () => LocalizedString
	/**
	 * Data2Resilience, urbane Resilienz, extreme Hitze, Dortmund, Klimawandel, biometeorologische Messung, gesellschaftliches Engagement, Hitzeresilienz, Stadtklima, Klimaanpassung
	 */
	keywords: () => LocalizedString
	/**
	 * RUBclim
	 */
	twitterHandle: () => LocalizedString
	/**
	 * Dieses Logging wurde von '{fileName}' aufgerufen
	 */
	log: (arg: { fileName: string }) => LocalizedString
	/**
	 * #007bff
	 */
	themeColor: () => LocalizedString
	headImages: {
		og: {
			/**
			 * Screenshot des Data2Resilience-Karten-Dashboards
			 */
			large: () => LocalizedString
			/**
			 * Logo des Data2Resilience-Projektes
			 */
			square: () => LocalizedString
		}
		/**
		 * Screenshot des Data2Resilience-Karten-Dashboards
		 */
		twitter: () => LocalizedString
	}
	errors: {
		/**
		 * Fehler
		 */
		genericErrorLabel: () => LocalizedString
		unexpectedError: {
			/**
			 * Unerwarteter Fehler
			 */
			label: () => LocalizedString
			/**
			 * Ups, es scheint, dass etwas schiefgelaufen ist: "{errorMessage}". Wir entschuldigen uns. Bitte versuchen Sie es erneut oder navigieren Sie zur Startseite.
			 */
			description: (arg: { errorMessage: string }) => LocalizedString
		}
		fourOhFour: {
			/**
			 * Seite nicht gefunden
			 */
			label: () => LocalizedString
			/**
			 * Ups, es scheint, dass die von Ihnen gesuchte Seite nicht existiert. Nichts ist schiefgelaufen, wir helfen Ihnen, auf den Weg zu kommen.
			 */
			description: () => LocalizedString
			/**
			 * Zur Startseite
			 */
			homepageLinkText: () => LocalizedString
		}
	}
	generic: {
		/**
		 * Mehr erfahren
		 */
		expand: () => LocalizedString
		/**
		 * Zusammenklappen
		 */
		collapse: () => LocalizedString
	}
	welcome: {
		/**
		 * Herzlich willkommen
		 */
		title: () => LocalizedString
		text: {
			/**
			 * Das Projekt Data2Resilience nutzt ein neues biometeorologisches Messnetzwerk zur Beobachtung und Vorhersage von Hitze und bezieht die Bürger frühzeitig ein, um Herausforderungen und Bedürfnisse in Dortmund zu adressieren. Dieses Dashboard ermöglicht Ihnen, Echtzeitdaten zum thermischen Komfort in der Stadt zu erkunden.
			 */
			'0': () => LocalizedString
		}
		buttons: {
			/**
			 * Verstanden, los geht's
			 */
			confirm: () => LocalizedString
			/**
			 * Einführung starten
			 */
			launchTour: () => LocalizedString
		}
		/**
		 * Einleitung erneut anzeigen
		 */
		expandButtonLabel: () => LocalizedString
	}
	navigation: {
		header: {
			/**
			 * Über dieses Dashboard
			 */
			about: () => LocalizedString
		}
		tabs: {
			/**
			 * Thermischer Komfort
			 */
			thermicalComfort: () => LocalizedString
			/**
			 * Aktuelle Messwerte
			 */
			actualMeasurements: () => LocalizedString
			/**
			 * Messstationen
			 */
			stations: () => LocalizedString
		}
	}
	pages: {
		thermicalComfort: {
			/**
			 * Wie warm fühlt sich deine Stadt an?
			 */
			title: () => LocalizedString
			intro: {
				/**
				 * Thermischer Komfort ist der Wohlfühlzustand, bei dem eine Person mit der thermischen Umgebung zufrieden ist. Das bedeutet, dass Temperatur, Luftfeuchtigkeit, Luftbewegung und Strahlungswärme in einem als angenehm empfundenen Bereich liegen. Er kann anhand verschiedener Indikatoren gemessen werden:
				 */
				'0': () => LocalizedString
			}
			/**
			 * Wähle einen Indikator, um die angezeigten Daten auf der Karte zu ändern.
			 */
			indicatorsNavAriaLabel: () => LocalizedString
		}
		measurements: {
			/**
			 * Was wird aktuell gemessen?
			 */
			title: () => LocalizedString
			intro: {
				/**
				 * Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
				 */
				'0': () => LocalizedString
				/**
				 * Aktuell Messwerte können sowohl für die Messstationen als auch für die einzelnen Stadtbezirke angezeigt werden.
				 */
				'1': () => LocalizedString
			}
		}
		stations: {
			/**
			 * Wie messen wir thermischen Komfort?
			 */
			title: () => LocalizedString
			intro: {
				/**
				 * Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
				 */
				'0': () => LocalizedString
			}
			stationsDescriptions: {
				wheather: {
					/**
					 * Wetterstation mit Blackglobe-Sensor
					 */
					title: () => LocalizedString
					/**
					 * Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
					 */
					description: () => LocalizedString
				}
				airTemperatureAndHumidity: {
					/**
					 * Lufttemperatur- und Feuchtigkeitssensor
					 */
					title: () => LocalizedString
					/**
					 * Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
					 */
					description: () => LocalizedString
				}
			}
		}
	}
	indicators: {
		utci: {
			/**
			 * Universeller Thermischer Klimaindex (UTCI)
			 */
			title: () => LocalizedString
			/**
			 * Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes.
			 */
			description: () => LocalizedString
			types: {
				byClass: {
					/**
					 * Nach Klasse
					 */
					title: () => LocalizedString
					/**
					 * Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes.
					 */
					description: () => LocalizedString
				}
				byValue: {
					/**
					 * Nach Wert
					 */
					title: () => LocalizedString
					/**
					 * Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes.
					 */
					description: () => LocalizedString
				}
			}
		}
		pet: {
			/**
			 * Physiologisch Äquivalente Temperatur (PET)
			 */
			title: () => LocalizedString
			/**
			 * Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes.
			 */
			description: () => LocalizedString
		}
		mrt: {
			/**
			 * Mittelwert der regionalen Temperatur (MRT)
			 */
			title: () => LocalizedString
			/**
			 * Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes.
			 */
			description: () => LocalizedString
		}
	}
}

export type Formatters = {}
