// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * D​a​t​a​2​R​e​s​i​l​i​e​n​c​e
	 */
	siteNameShort: string
	/**
	 * D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​ ​T​e​a​m
	 */
	author: string
	/**
	 * E​n​h​a​n​c​i​n​g​ ​U​r​b​a​n​ ​R​e​s​i​l​i​e​n​c​e​ ​A​g​a​i​n​s​t​ ​E​x​t​r​e​m​e​ ​H​e​a​t​ ​i​n​ ​D​o​r​t​m​u​n​d
	 */
	siteSubtitle: string
	/**
	 * D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​ ​|​ ​E​n​h​a​n​c​i​n​g​ ​U​r​b​a​n​ ​R​e​s​i​l​i​e​n​c​e​ ​A​g​a​i​n​s​t​ ​E​x​t​r​e​m​e​ ​H​e​a​t​ ​i​n​ ​D​o​r​t​m​u​n​d
	 */
	siteNameLong: string
	/**
	 * D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​ ​i​s​ ​a​ ​p​r​o​j​e​c​t​ ​a​i​m​e​d​ ​a​t​ ​i​m​p​r​o​v​i​n​g​ ​u​r​b​a​n​ ​r​e​s​i​l​i​e​n​c​e​ ​a​g​a​i​n​s​t​ ​e​x​t​r​e​m​e​ ​h​e​a​t​ ​i​n​ ​D​o​r​t​m​u​n​d​ ​t​h​r​o​u​g​h​ ​i​n​n​o​v​a​t​i​v​e​ ​b​i​o​m​e​t​e​o​r​o​l​o​g​i​c​a​l​ ​m​e​a​s​u​r​e​m​e​n​t​ ​n​e​t​w​o​r​k​s​ ​a​n​d​ ​c​o​m​m​u​n​i​t​y​ ​e​n​g​a​g​e​m​e​n​t​.​ ​L​e​a​r​n​ ​m​o​r​e​ ​a​b​o​u​t​ ​o​u​r​ ​i​n​i​t​i​a​t​i​v​e​s​ ​a​n​d​ ​r​e​s​u​l​t​s​.
	 */
	siteDescription: string
	/**
	 * D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​,​ ​u​r​b​a​n​ ​r​e​s​i​l​i​e​n​c​e​,​ ​e​x​t​r​e​m​e​ ​h​e​a​t​,​ ​D​o​r​t​m​u​n​d​,​ ​c​l​i​m​a​t​e​ ​c​h​a​n​g​e​,​ ​b​i​o​m​e​t​e​o​r​o​l​o​g​i​c​a​l​ ​m​e​a​s​u​r​e​m​e​n​t​,​ ​c​o​m​m​u​n​i​t​y​ ​e​n​g​a​g​e​m​e​n​t​,​ ​h​e​a​t​ ​r​e​s​i​l​i​e​n​c​e​,​ ​u​r​b​a​n​ ​c​l​i​m​a​t​e​,​ ​c​l​i​m​a​t​e​ ​a​d​a​p​t​a​t​i​o​n
	 */
	keywords: string
	/**
	 * R​U​B​c​l​i​m
	 */
	twitterHandle: string
	/**
	 * T​h​i​s​ ​l​o​g​ ​w​a​s​ ​c​a​l​l​e​d​ ​f​r​o​m​ ​'​{​f​i​l​e​N​a​m​e​}​'
	 * @param {string} fileName
	 */
	log: RequiredParams<'fileName'>
	/**
	 * #​0​0​7​b​f​f
	 */
	themeColor: string
	headImages: {
		og: {
			/**
			 * S​c​r​e​e​n​s​h​o​t​ ​o​f​ ​t​h​e​ ​D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​ ​m​a​p​ ​d​a​s​h​b​o​a​r​d
			 */
			large: string
			/**
			 * L​o​g​o​ ​o​f​ ​t​h​e​ ​D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​ ​p​r​o​j​e​c​t
			 */
			square: string
		}
		/**
		 * S​c​r​e​e​n​s​h​o​t​ ​o​f​ ​t​h​e​ ​D​a​t​a​2​R​e​s​i​l​i​e​n​c​e​ ​m​a​p​ ​d​a​s​h​b​o​a​r​d
		 */
		twitter: string
	}
}

export type TranslationFunctions = {
	/**
	 * Data2Resilience
	 */
	siteNameShort: () => LocalizedString
	/**
	 * Data2Resilience Team
	 */
	author: () => LocalizedString
	/**
	 * Enhancing Urban Resilience Against Extreme Heat in Dortmund
	 */
	siteSubtitle: () => LocalizedString
	/**
	 * Data2Resilience | Enhancing Urban Resilience Against Extreme Heat in Dortmund
	 */
	siteNameLong: () => LocalizedString
	/**
	 * Data2Resilience is a project aimed at improving urban resilience against extreme heat in Dortmund through innovative biometeorological measurement networks and community engagement. Learn more about our initiatives and results.
	 */
	siteDescription: () => LocalizedString
	/**
	 * Data2Resilience, urban resilience, extreme heat, Dortmund, climate change, biometeorological measurement, community engagement, heat resilience, urban climate, climate adaptation
	 */
	keywords: () => LocalizedString
	/**
	 * RUBclim
	 */
	twitterHandle: () => LocalizedString
	/**
	 * This log was called from '{fileName}'
	 */
	log: (arg: { fileName: string }) => LocalizedString
	/**
	 * #007bff
	 */
	themeColor: () => LocalizedString
	headImages: {
		og: {
			/**
			 * Screenshot of the Data2Resilience map dashboard
			 */
			large: () => LocalizedString
			/**
			 * Logo of the Data2Resilience project
			 */
			square: () => LocalizedString
		}
		/**
		 * Screenshot of the Data2Resilience map dashboard
		 */
		twitter: () => LocalizedString
	}
}

export type Formatters = {}
